define(function(){
	return [
		{
			title:"eeeeeeeeeeeeeeeeee",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			title:"aaaaaaa",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			title:"bbbbbbbbbbbbbb",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			title:"cccccccccccccc",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			title:"ddddddddddddddddd",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			title:"eeeeeeeeeeeeeeeeee",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		}
	]
})