define(function(){
	return [
		{
			type:"danxuan",
			title:"eeeeeeeeeeeeeeeeee",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"A"
		},
		{
			type:"danxuan",
			title:"aaaaaaa",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"B"
		},
		{
			type:"danxuan",
			title:"eeeeeeeeeeeeeeeeee",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			type:"duoxuan",
			title:"aaaaaaa",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			type:"duoxuan",
			title:"aaaaaaa",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			type:"duoxuan",
			title:"aaaaaaa",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			type:"duoxuan",
			title:"aaaaaaa",
			options:["asdfadf","adfasdf","asdfasdf","asdfasdfasdf"],
			answer:"AB"
		},
		{
			type:"panduan",
			title:"aaaaaaa",
			answer:true
		},
		{
			type:"panduan",
			title:"aaaaaaa",
			answer:true
		},
		{
			type:"panduan",
			title:"aaaaaaa",
			answer:true
		},
		{
			type:"tiankong",
			title:"aaaaaaa",
			answer:"aaaaa"
		},
		{
			type:"tiankong",
			title:"aaaaaaa",
			answer:"bbbbb"
		},
		{
			type:"tiankong",
			title:"aaaaaaa",
			answer:"ccccc"
		}
	]
})